#!/usr/bin/env python3
"""research/tools/account_tape.py — regenerate docs/images/account_tape.svg.

The README's "tuition" chart: the whole practice-account balance history from
$100k (2026-03-22) through the -84% research tuition to today, one honest line.
Built from broker transaction balances (the only truth), so it can be
regenerated any time instead of going stale. Theme-neutral SVG (mid-gray +
amber accent) matching the original hand-built chart's aesthetic.

Run on EC2 (needs OANDA creds): python3 research/tools/account_tape.py
"""
from __future__ import annotations
import json, os, urllib.request
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "docs" / "images" / "account_tape.svg"

GRAY, LGRAY, AMBER, GREEN = "#808a94", "#9aa2ab", "#cf8e3e", "#3fb950"

ERAS = [  # (iso_date, label)
    ("2026-03-22", "V1"), ("2026-04-14", "V2"), ("2026-05-06", "V3"),
    ("2026-06-11", "V4"), ("2026-06-18", "V5"), ("2026-07-18", "V6 live"),
    ("2026-07-27", "governor"),
]


def _secrets():
    d = {}
    for ln in open(os.path.expanduser("~/.openclaw/secrets.env")):
        if "=" in ln and not ln.strip().startswith("#"):
            k, v = ln.rstrip("\n").split("=", 1)
            d[k.strip()] = v.strip()
    return d


def balances():
    s = _secrets()
    url, tok, acct = s["OANDA_API_URL"], s["OANDA_API_TOKEN"], s["OANDA_ACCOUNT_ID"]

    def api(p):
        r = urllib.request.Request(url + p, headers={"Authorization": "Bearer " + tok})
        return json.loads(urllib.request.urlopen(r, timeout=30).read())

    last_id = int(api(f"/v3/accounts/{acct}/summary")["account"]["lastTransactionID"])
    daily = {}   # date -> last balance seen that day
    frm = 1
    while frm <= last_id:
        to = min(frm + 999, last_id)
        for t in api(f"/v3/accounts/{acct}/transactions/idrange?from={frm}&to={to}"
                     ).get("transactions", []):
            b = t.get("accountBalance")
            if b is not None:
                daily[t["time"][:10]] = float(b)
        frm = to + 1
    return sorted(daily.items())


def make_svg(series):
    W, H = 900, 470
    left, right, top, bot = 60, 20, 70, 50
    pw, ph = W - left - right, H - top - bot
    d0 = datetime.fromisoformat(series[0][0]).timestamp()
    d1 = datetime.fromisoformat(series[-1][0]).timestamp()
    vmax = max(v for _, v in series)
    vmin = min(v for _, v in series)
    pad = (vmax - vmin) * 0.06
    vmax += pad; vmin -= pad

    def X(iso): return left + pw * (datetime.fromisoformat(iso).timestamp() - d0) / (d1 - d0)
    def Y(v):   return top + ph * (1 - (v - vmin) / (vmax - vmin))

    lo_date, lo_val = min(series, key=lambda kv: kv[1])
    cur_date, cur_val = series[-1]
    pts = " ".join(f"{X(d):.1f},{Y(v):.1f}" for d, v in series)

    grid = ""
    for gv in (100000, 80000, 60000, 40000, 20000):
        if vmin < gv < vmax:
            gy = Y(gv)
            grid += (f'<line x1="{left}" y1="{gy:.1f}" x2="{W-right}" y2="{gy:.1f}" '
                     f'stroke="{GRAY}" stroke-opacity="0.18" stroke-width="1"/>'
                     f'<text x="{left-8}" y="{gy+4:.1f}" text-anchor="end" fill="{LGRAY}" '
                     f'font-size="10">${gv//1000}k</text>')

    eras = ""
    for iso, label in ERAS:
        if not (series[0][0] <= iso <= series[-1][0]):
            continue
        ex = X(iso)
        eras += (f'<line x1="{ex:.1f}" y1="{top}" x2="{ex:.1f}" y2="{H-bot}" '
                 f'stroke="{GRAY}" stroke-opacity="0.3" stroke-dasharray="3,4" stroke-width="1"/>'
                 f'<text x="{ex+3:.1f}" y="{top+12}" fill="{LGRAY}" font-size="9.5">{label}</text>')

    svg = f'''<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif">
  <!-- Generated by research/tools/account_tape.py from broker transaction balances.
       Theme-neutral: mid-gray reads on light AND dark; amber accent; green = current era. -->
  <text x="{W//2}" y="30" text-anchor="middle" fill="{GRAY}" font-size="18" font-weight="700">The tape: the whole account, uncurated</text>
  <text x="{W//2}" y="50" text-anchor="middle" fill="{LGRAY}" font-size="11" font-style="italic">Practice-account balance, {series[0][0]} → {cur_date} · every era, including the −84% tuition</text>
  {grid}
  {eras}
  <polyline points="{pts}" fill="none" stroke="{AMBER}" stroke-width="2"/>
  <circle cx="{X(lo_date):.1f}" cy="{Y(lo_val):.1f}" r="3.5" fill="{AMBER}"/>
  <text x="{X(lo_date):.1f}" y="{Y(lo_val)+16:.1f}" text-anchor="middle" fill="{AMBER}" font-size="10.5" font-weight="700">${lo_val:,.0f} low · {lo_date}</text>
  <circle cx="{X(cur_date):.1f}" cy="{Y(cur_val):.1f}" r="3.5" fill="{GREEN}"/>
  <text x="{X(cur_date)-6:.1f}" y="{Y(cur_val)-10:.1f}" text-anchor="end" fill="{GREEN}" font-size="10.5" font-weight="700">${cur_val:,.0f} · {cur_date}</text>
  <text x="{left}" y="{H-16}" fill="{LGRAY}" font-size="9.5">Source: broker transaction balances · regenerate: research/tools/account_tape.py</text>
</svg>
'''
    OUT.write_text(svg)
    print(f"wrote {OUT} — {len(series)} days, low ${lo_val:,.0f} ({lo_date}), now ${cur_val:,.0f}")


if __name__ == "__main__":
    make_svg(balances())
